# Generated by Django 5.0.3 on 2024-04-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='id',
            new_name='issueid',
        ),
    ]
